# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
script:
- xcodebuild clean -workspace Example/ios-dpp.xcworkspace -scheme ios-dpp-Example
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ios-dpp.xcworkspace -scheme ios-dpp-Example -destination 'platform=iOS Simulator,name=iPhone 8' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
